FROM python:3.12-slim
WORKDIR /app
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install debugpy
COPY app/ .
COPY common_services/ common_services/
CMD ["python", "-Xfrozen_modules=off", "-m", "debugpy", "--listen", "0.0.0.0:5679", "--wait-for-client", "-m", "flask", "run", "--no-debugger", "--host=0.0.0.0", "--port=5000"]
