services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: ["azurite", "-l", "/data", "--blobHost", "0.0.0.0", "--queueHost", "0.0.0.0", "--tableHost", "0.0.0.0", "--loose", "--skipApiVersionCheck"]
    restart: unless-stopped
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
  queue_worker:
    image: queue_worker
    ports:
      - 5678:5678
    restart: unless-stopped
    depends_on:
      - azurite
  web-api:
    build:
      context: .
      dockerfile: app/Dockerfile
    pull_policy: build
    restart: unless-stopped
    ports:
      - 5050:5000
volumes:
  postgres_data:
